# Site settings
title: haku Docs
url: "http://localhost:4000" # the base hostname & protocol for your site

paginate: 5

email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here, 
baseurl: "" # the subpath of your site, e.g. /blog/

twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
# markdown: rdiscount
permalink: pretty
highlighter: true